Update Cargo dependencies and flake inputs
Rust 1.80.0 breaks the time crate (NixOS/nixpkgs#332957):

> error[E0282]: type annotations needed for `Box<_>`
>   --> /build/cargo-vendor-dir/time-0.3.30/src/format_description/parse/mod.rs:83:9
>    |
> 83 |     let items = format_items
>    |         ^^^^^
> ...
> 86 |     Ok(items.into())
>    |              ---- type must be known at this point
>    |
> help: consider giving `items` an explicit type, where the placeholders `_` are specified
>    |
> 83 |     let items: Box<_> = format_items
>    |              ++++++++

Updating both Cargo dependencies and the nixpkgs snapshot fixes it.